var GreekSonship={
    "Mat 1:1": "The book of the generation of Jesus Christ, the son G5207 of David, the son G5207 of Abraham.",
    "Mat 1:20": "But while he thought on these things, behold, the angel of the Lord appeared unto him in a dream, saying, Joseph, thou son G5207 of David, fear not to take unto thee Mary thy wife: for that which is conceived in her is of the Holy Ghost.",
    "Mat 1:21": "And she shall bring forth a son, G5207 and thou shalt call his name JESUS: for he shall save his people from their sins.",
    "Mat 1:23": "Behold, a virgin shall be with child, and shall bring forth a son, G5207 and they shall call his name Emmanuel, which being interpreted is, God with us.",
    "Mat 1:25": "And knew her not till she had brought forth her firstborn son: G5207 and he called his name JESUS.",
    "Mat 2:15": "And was there until the death of Herod: that it might be fulfilled which was spoken of the Lord by the prophet, saying, Out of Egypt have I called my son. G5207",
    "Mat 3:17": "And lo a voice from heaven, saying, This is my beloved Son, G5207 in whom I am well pleased.",
    "Mat 4:3": "And when the tempter came to him, he said, If thou be the Son G5207 of God, command that these stones be made bread.",
    "Mat 4:6": "And saith unto him, If thou be the Son G5207 of God, cast thyself down: for it is written, He shall give his angels charge concerning thee: and in their hands they shall bear thee up, lest at any time thou dash thy foot against a stone.",
    "Mat 5:9": "Blessed are the peacemakers: for they shall be called the children G5207 of God.",
    "Mat 5:45": "That ye may be the children G5207 of your Father which is in heaven: for he maketh his sun to rise on the evil and on the good, and sendeth rain on the just and on the unjust.",
    "Mat 7:9": "Or what man is there of you, whom if his son G5207 ask bread, will he give him a stone?",
    "Mat 8:12": "But the children G5207 of the kingdom shall be cast out into outer darkness: there shall be weeping and gnashing of teeth.",
    "Mat 8:20": "And Jesus saith unto him, The foxes have holes, and the birds of the air have nests; but the Son G5207 of man hath not where to lay his head.",
    "Mat 8:29": "And, behold, they cried out, saying, What have we to do with thee, Jesus, thou Son G5207 of God? art thou come hither to torment us before the time?",
    "Mat 9:6": "But that ye may know that the Son G5207 of man hath power on earth to forgive sins, (then saith he to the sick of the palsy,) Arise, take up thy bed, and go unto thine house.",
    "Mat 9:15": "And Jesus said unto them, Can the children G5207 of the bridechamber mourn, as long as the bridegroom is with them? but the days will come, when the bridegroom shall be taken from them, and then shall they fast.",
    "Mat 9:27": "And when Jesus departed thence, two blind men followed him, crying, and saying, Thou Son G5207 of David, have mercy on us.",
    "Mat 10:23": "But when they persecute you in this city, flee ye into another: for verily I say unto you, Ye shall not have gone over the cities of Israel, till the Son G5207 of man be come.",
    "Mat 10:37": "He that loveth father or mother more than me is not worthy of me: and he that loveth son G5207 or daughter more than me is not worthy of me.",
    "Mat 11:19": "The Son G5207 of man came eating and drinking, and they say, Behold a man gluttonous, and a winebibber, a friend of publicans and sinners. But wisdom is justified of her children.",
    "Mat 11:27": "All things are delivered unto me of my Father: and no man knoweth the Son, G5207 but the Father; neither knoweth any man the Father, save the Son, G5207 and he to whomsoever the Son G5207 will reveal him.",
    "Mat 12:8": "For the Son G5207 of man is Lord even of the sabbath day.",
    "Mat 12:23": "And all the people were amazed, and said, Is not this the son G5207 of David?",
    "Mat 12:27": "And if I by Beelzebub cast out devils, by whom do your children G5207 cast them out? therefore they shall be your judges.",
    "Mat 12:32": "And whosoever speaketh a word against the Son G5207 of man, it shall be forgiven him: but whosoever speaketh against the Holy Ghost, it shall not be forgiven him, neither in this world, neither in the world to come.",
    "Mat 12:40": "For as Jonas was three days and three nights in the whale's belly; so shall the Son G5207 of man be three days and three nights in the heart of the earth.",
    "Mat 13:37": "He answered and said unto them, He that soweth the good seed is the Son G5207 of man;",
    "Mat 13:38": "The field is the world; the good seed are the children G5207 of the kingdom; but the tares are the children G5207 of the wicked one;",
    "Mat 13:41": "The Son G5207 of man shall send forth his angels, and they shall gather out of his kingdom all things that offend, and them which do iniquity;",
    "Mat 13:55": "Is not this the carpenter's son? G5207 is not his mother called Mary? and his brethren, James, and Joses, and Simon, and Judas?",
    "Mat 14:33": "Then they that were in the ship came and worshipped him, saying, Of a truth thou art the Son G5207 of God.",
    "Mat 15:22": "And, behold, a woman of Canaan came out of the same coasts, and cried unto him, saying, Have mercy on me, O Lord, thou Son G5207 of David; my daughter is grievously vexed with a devil.",
    "Mat 16:13": "When Jesus came into the coasts of Caesarea Philippi, he asked his disciples, saying, Whom do men say that I the Son G5207 of man am?",
    "Mat 16:16": "And Simon Peter answered and said, Thou art the Christ, the Son G5207 of the living God.",
    "Mat 16:27": "For the Son G5207 of man shall come in the glory of his Father with his angels; and then he shall reward every man according to his works.",
    "Mat 16:28": "Verily I say unto you, There be some standing here, which shall not taste of death, till they see the Son G5207 of man coming in his kingdom.",
    "Mat 17:5": "While he yet spake, behold, a bright cloud overshadowed them: and behold a voice out of the cloud, which said, This is my beloved Son, G5207 in whom I am well pleased; hear ye him.",
    "Mat 17:9": "And as they came down from the mountain, Jesus charged them, saying, Tell the vision to no man, until the Son G5207 of man be risen again from the dead.",
    "Mat 17:12": "But I say unto you, That Elias is come already, and they knew him not, but have done unto him whatsoever they listed. Likewise shall also the Son G5207 of man suffer of them.",
    "Mat 17:15": "Lord, have mercy on my son: G5207 for he is lunatick, and sore vexed: for ofttimes he falleth into the fire, and oft into the water.",
    "Mat 17:22": "And while they abode in Galilee, Jesus said unto them, The Son G5207 of man shall be betrayed into the hands of men:",
    "Mat 17:25": "He saith, Yes. And when he was come into the house, Jesus prevented him, saying, What thinkest thou, Simon? of whom do the kings of the earth take custom or tribute? of their own children, G5207 or of strangers?",
    "Mat 17:26": "Peter saith unto him, Of strangers. Jesus saith unto him, Then are the children G5207 free.",
    "Mat 18:11": "For the Son G5207 of man is come to save that which was lost.",
    "Mat 19:28": "And Jesus said unto them, Verily I say unto you, That ye which have followed me, in the regeneration when the Son G5207 of man shall sit in the throne of his glory, ye also shall sit upon twelve thrones, judging the twelve tribes of Israel.",
    "Mat 20:18": "Behold, we go up to Jerusalem; and the Son G5207 of man shall be betrayed unto the chief priests and unto the scribes, and they shall condemn him to death,",
    "Mat 20:20": "Then came to him the mother of Zebedee's children G5207 with her sons, G5207 worshipping him, and desiring a certain thing of him.",
    "Mat 20:21": "And he said unto her, What wilt thou? She saith unto him, Grant that these my two sons G5207 may sit, the one on thy right hand, and the other on the left, in thy kingdom.",
    "Mat 20:28": "Even as the Son G5207 of man came not to be ministered unto, but to minister, and to give his life a ransom for many.",
    "Mat 20:30": "And, behold, two blind men sitting by the way side, when they heard that Jesus passed by, cried out, saying, Have mercy on us, O Lord, thou Son G5207 of David.",
    "Mat 20:31": "And the multitude rebuked them, because they should hold their peace: but they cried the more, saying, Have mercy on us, O Lord, thou Son G5207 of David.",
    "Mat 21:5": "Tell ye the daughter of Sion, Behold, thy King cometh unto thee, meek, and sitting upon an ass, and a colt the foal G5207 of an ass.",
    "Mat 21:9": "And the multitudes that went before, and that followed, cried, saying, Hosanna to the Son G5207 of David: Blessed is he that cometh in the name of the Lord; Hosanna in the highest.",
    "Mat 21:15": "And when the chief priests and scribes saw the wonderful things that he did, and the children crying in the temple, and saying, Hosanna to the Son G5207 of David; they were sore displeased,",
    "Mat 21:37": "But last of all he sent unto them his son, G5207 saying, They will reverence my son. G5207",
    "Mat 21:38": "But when the husbandmen saw the son, G5207 they said among themselves, This is the heir; come, let us kill him, and let us seize on his inheritance.",
    "Mat 22:2": "The kingdom of heaven is like unto a certain king, which made a marriage for his son, G5207",
    "Mat 22:42": "Saying, What think ye of Christ? whose son G5207 is he? They say unto him, The Son of David.",
    "Mat 22:45": "If David then call him Lord, how is he his son? G5207",
    "Mat 23:15": "Woe unto you, scribes and Pharisees, hypocrites! for ye compass sea and land to make one proselyte, and when he is made, ye make him twofold more the child G5207 of hell than yourselves.",
    "Mat 23:31": "Wherefore ye be witnesses unto yourselves, that ye are the children G5207 of them which killed the prophets.",
    "Mat 23:35": "That upon you may come all the righteous blood shed upon the earth, from the blood of righteous Abel unto the blood of Zacharias son G5207 of Barachias, whom ye slew between the temple and the altar.",
    "Mat 24:27": "For as the lightning cometh out of the east, and shineth even unto the west; so shall also the coming of the Son G5207 of man be.",
    "Mat 24:30": "And then shall appear the sign of the Son G5207 of man in heaven: and then shall all the tribes of the earth mourn, and they shall see the Son G5207 of man coming in the clouds of heaven with power and great glory.",
    "Mat 24:37": "But as the days of Noe were, so shall also the coming of the Son G5207 of man be.",
    "Mat 24:39": "And knew not until the flood came, and took them all away; so shall also the coming of the Son G5207 of man be.",
    "Mat 24:44": "Therefore be ye also ready: for in such an hour as ye think not the Son G5207 of man cometh.",
    "Mat 25:13": "Watch therefore, for ye know neither the day nor the hour wherein the Son G5207 of man cometh.",
    "Mat 25:31": "When the Son G5207 of man shall come in his glory, and all the holy angels with him, then shall he sit upon the throne of his glory:",
    "Mat 26:2": "Ye know that after two days is the feast of the passover, and the Son G5207 of man is betrayed to be crucified.",
    "Mat 26:24": "The Son G5207 of man goeth as it is written of him: but woe unto that man by whom the Son G5207 of man is betrayed! it had been good for that man if he had not been born.",
    "Mat 26:37": "And he took with him Peter and the two sons G5207 of Zebedee, and began to be sorrowful and very heavy.",
    "Mat 26:45": "Then cometh he to his disciples, and saith unto them, Sleep on now, and take your rest: behold, the hour is at hand, and the Son G5207 of man is betrayed into the hands of sinners.",
    "Mat 26:63": "But Jesus held his peace. And the high priest answered and said unto him, I adjure thee by the living God, that thou tell us whether thou be the Christ, the Son G5207 of God.",
    "Mat 26:64": "Jesus saith unto him, Thou hast said: nevertheless I say unto you, Hereafter shall ye see the Son G5207 of man sitting on the right hand of power, and coming in the clouds of heaven.",
    "Mat 27:9": "Then was fulfilled that which was spoken by Jeremy the prophet, saying, And they took the thirty pieces of silver, the price of him that was valued, whom they of the children G5207 of Israel did value;",
    "Mat 27:40": "And saying, Thou that destroyest the temple, and buildest it in three days, save thyself. If thou be the Son G5207 of God, come down from the cross.",
    "Mat 27:43": "He trusted in God; let him deliver him now, if he will have him: for he said, I am the Son G5207 of God.",
    "Mat 27:54": "Now when the centurion, and they that were with him, watching Jesus, saw the earthquake, and those things that were done, they feared greatly, saying, Truly this was the Son G5207 of God.",
    "Mat 27:56": "Among which was Mary Magdalene, and Mary the mother of James and Joses, and the mother of Zebedee's children. G5207",
    "Mat 28:19": "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, G5207 and of the Holy Ghost:",
    "Mar 1:1": "The beginning of the gospel of Jesus Christ, the Son G5207 of God;",
    "Mar 1:11": "And there came a voice from heaven, saying, Thou art my beloved Son, G5207 in whom I am well pleased.",
    "Mar 2:10": "But that ye may know that the Son G5207 of man hath power on earth to forgive sins, (he saith to the sick of the palsy,)",
    "Mar 2:19": "And Jesus said unto them, Can the children G5207 of the bridechamber fast, while the bridegroom is with them? as long as they have the bridegroom with them, they cannot fast.",
    "Mar 2:28": "Therefore the Son G5207 of man is Lord also of the sabbath.",
    "Mar 3:11": "And unclean spirits, when they saw him, fell down before him, and cried, saying, Thou art the Son G5207 of God.",
    "Mar 3:17": "And James the son of Zebedee, and John the brother of James; and he surnamed them Boanerges, which is, The sons G5207 of thunder:",
    "Mar 3:28": "Verily I say unto you, All sins shall be forgiven unto the sons G5207 of men, and blasphemies wherewith soever they shall blaspheme:",
    "Mar 5:7": "And cried with a loud voice, and said, What have I to do with thee, Jesus, thou Son G5207 of the most high God? I adjure thee by God, that thou torment me not.",
    "Mar 6:3": "Is not this the carpenter, the son G5207 of Mary, the brother of James, and Joses, and of Juda, and Simon? and are not his sisters here with us? And they were offended at him.",
    "Mar 8:31": "And he began to teach them, that the Son G5207 of man must suffer many things, and be rejected of the elders, and of the chief priests, and scribes, and be killed, and after three days rise again.",
    "Mar 8:38": "Whosoever therefore shall be ashamed of me and of my words in this adulterous and sinful generation; of him also shall the Son G5207 of man be ashamed, when he cometh in the glory of his Father with the holy angels.",
    "Mar 9:7": "And there was a cloud that overshadowed them: and a voice came out of the cloud, saying, This is my beloved Son: G5207 hear him.",
    "Mar 9:9": "And as they came down from the mountain, he charged them that they should tell no man what things they had seen, till the Son G5207 of man were risen from the dead.",
    "Mar 9:12": "And he answered and told them, Elias verily cometh first, and restoreth all things; and how it is written of the Son G5207 of man, that he must suffer many things, and be set at nought.",
    "Mar 9:17": "And one of the multitude answered and said, Master, I have brought unto thee my son, G5207 which hath a dumb spirit;",
    "Mar 9:31": "For he taught his disciples, and said unto them, The Son G5207 of man is delivered into the hands of men, and they shall kill him; and after that he is killed, he shall rise the third day.",
    "Mar 10:33": "Saying, Behold, we go up to Jerusalem; and the Son G5207 of man shall be delivered unto the chief priests, and unto the scribes; and they shall condemn him to death, and shall deliver him to the Gentiles:",
    "Mar 10:35": "And James and John, the sons G5207 of Zebedee, come unto him, saying, Master, we would that thou shouldest do for us whatsoever we shall desire.",
    "Mar 10:45": "For even the Son G5207 of man came not to be ministered unto, but to minister, and to give his life a ransom for many.",
    "Mar 10:46": "And they came to Jericho: and as he went out of Jericho with his disciples and a great number of people, blind Bartimaeus, the son G5207 of Timaeus, sat by the highway side begging.",
    "Mar 10:47": "And when he heard that it was Jesus of Nazareth, he began to cry out, and say, Jesus, thou Son G5207 of David, have mercy on me.",
    "Mar 10:48": "And many charged him that he should hold his peace: but he cried the more a great deal, Thou Son G5207 of David, have mercy on me.",
    "Mar 12:6": "Having yet therefore one son, G5207 his wellbeloved, he sent him also last unto them, saying, They will reverence my son. G5207",
    "Mar 12:35": "And Jesus answered and said, while he taught in the temple, How say the scribes that Christ is the Son G5207 of David?",
    "Mar 12:37": "David therefore himself calleth him Lord; and whence is he then his son? G5207 And the common people heard him gladly.",
    "Mar 13:26": "And then shall they see the Son G5207 of man coming in the clouds with great power and glory.",
    "Mar 13:32": "But of that day and that hour knoweth no man, no, not the angels which are in heaven, neither the Son, G5207 but the Father.",
    "Mar 14:21": "The Son G5207 of man indeed goeth, as it is written of him: but woe to that man by whom the Son G5207 of man is betrayed! good were it for that man if he had never been born.",
    "Mar 14:41": "And he cometh the third time, and saith unto them, Sleep on now, and take your rest: it is enough, the hour is come; behold, the Son G5207 of man is betrayed into the hands of sinners.",
    "Mar 14:61": "But he held his peace, and answered nothing. Again the high priest asked him, and said unto him, Art thou the Christ, the Son G5207 of the Blessed?",
    "Mar 14:62": "And Jesus said, I am: and ye shall see the Son G5207 of man sitting on the right hand of power, and coming in the clouds of heaven.",
    "Mar 15:39": "And when the centurion, which stood over against him, saw that he so cried out, and gave up the ghost, he said, Truly this man was the Son G5207 of God.",
    "Luk 1:13": "But the angel said unto him, Fear not, Zacharias: for thy prayer is heard; and thy wife Elisabeth shall bear thee a son, G5207 and thou shalt call his name John.",
    "Luk 1:16": "And many of the children G5207 of Israel shall he turn to the Lord their God.",
    "Luk 1:31": "And, behold, thou shalt conceive in thy womb, and bring forth a son, G5207 and shalt call his name JESUS.",
    "Luk 1:32": "He shall be great, and shall be called the Son G5207 of the Highest: and the Lord God shall give unto him the throne of his father David:",
    "Luk 1:35": "And the angel answered and said unto her, The Holy Ghost shall come upon thee, and the power of the Highest shall overshadow thee: therefore also that holy thing which shall be born of thee shall be called the Son G5207 of God.",
    "Luk 1:36": "And, behold, thy cousin Elisabeth, she hath also conceived a son G5207 in her old age: and this is the sixth month with her, who was called barren.",
    "Luk 1:57": "Now Elisabeth's full time came that she should be delivered; and she brought forth a son. G5207",
    "Luk 2:7": "And she brought forth her firstborn son, G5207 and wrapped him in swaddling clothes, and laid him in a manger; because there was no room for them in the inn.",
    "Luk 3:2": "Annas and Caiaphas being the high priests, the word of God came unto John the son G5207 of Zacharias in the wilderness.",
    "Luk 3:22": "And the Holy Ghost descended in a bodily shape like a dove upon him, and a voice came from heaven, which said, Thou art my beloved Son; G5207 in thee I am well pleased.",
    "Luk 3:23": "And Jesus himself began to be about thirty years of age, being (as was supposed ) the son G5207 of Joseph, which was the son of Heli,",
    "Luk 4:3": "And the devil said unto him, If thou be the Son G5207 of God, command this stone that it be made bread.",
    "Luk 4:9": "And he brought him to Jerusalem, and set him on a pinnacle of the temple, and said unto him, If thou be the Son G5207 of God, cast thyself down from hence:",
    "Luk 4:22": "And all bare him witness, and wondered at the gracious words which proceeded out of his mouth. And they said, Is not this Joseph's son? G5207",
    "Luk 4:41": "And devils also came out of many, crying out, and saying, Thou art Christ the Son G5207 of God. And he rebuking them suffered them not to speak: for they knew that he was Christ.",
    "Luk 5:10": "And so was also James, and John, the sons G5207 of Zebedee, which were partners with Simon. And Jesus said unto Simon, Fear not; from henceforth thou shalt catch men.",
    "Luk 5:24": "But that ye may know that the Son G5207 of man hath power upon earth to forgive sins, (he said unto the sick of the palsy,) I say unto thee, Arise, and take up thy couch, and go into thine house.",
    "Luk 5:34": "And he said unto them, Can ye make the children G5207 of the bridechamber fast, while the bridegroom is with them?",
    "Luk 6:5": "And he said unto them, That the Son G5207 of man is Lord also of the sabbath.",
    "Luk 6:22": "Blessed are ye, when men shall hate you, and when they shall separate you from their company, and shall reproach you, and cast out your name as evil, for the Son G5207 of man's sake.",
    "Luk 6:35": "But love ye your enemies, and do good, and lend, hoping for nothing again; and your reward shall be great, and ye shall be the children G5207 of the Highest: for he is kind unto the unthankful and to the evil.",
    "Luk 7:12": "Now when he came nigh to the gate of the city, behold, there was a dead man carried out, the only son G5207 of his mother, and she was a widow: and much people of the city was with her.",
    "Luk 7:34": "The Son G5207 of man is come eating and drinking; and ye say, Behold a gluttonous man, and a winebibber, a friend of publicans and sinners!",
    "Luk 8:28": "When he saw Jesus, he cried out, and fell down before him, and with a loud voice said, What have I to do with thee, Jesus, thou Son G5207 of God most high? I beseech thee, torment me not.",
    "Luk 9:22": "Saying, The Son G5207 of man must suffer many things, and be rejected of the elders and chief priests and scribes, and be slain, and be raised the third day.",
    "Luk 9:26": "For whosoever shall be ashamed of me and of my words, of him shall the Son G5207 of man be ashamed, when he shall come in his own glory, and in his Father's, and of the holy angels.",
    "Luk 9:35": "And there came a voice out of the cloud, saying, This is my beloved Son: G5207 hear him.",
    "Luk 9:38": "And, behold, a man of the company cried out, saying, Master, I beseech thee, look upon my son: G5207 for he is mine only child.",
    "Luk 9:41": "And Jesus answering said, O faithless and perverse generation, how long shall I be with you, and suffer you? Bring thy son G5207 hither.",
    "Luk 9:44": "Let these sayings sink down into your ears: for the Son G5207 of man shall be delivered into the hands of men.",
    "Luk 9:56": "For the Son G5207 of man is not come to destroy men's lives, but to save them. And they went to another village.",
    "Luk 9:58": "And Jesus said unto him, Foxes have holes, and birds of the air have nests; but the Son G5207 of man hath not where to lay his head.",
    "Luk 10:6": "And if the son G5207 of peace be there, your peace shall rest upon it: if not, it shall turn to you again.",
    "Luk 10:22": "All things are delivered to me of my Father: and no man knoweth who the Son G5207 is, but the Father; and who the Father is, but the Son, G5207 and he to whom the Son G5207 will reveal him.",
    "Luk 11:11": "If a son G5207 shall ask bread of any of you that is a father, will he give him a stone? or if he ask a fish, will he for a fish give him a serpent?",
    "Luk 11:19": "And if I by Beelzebub cast out devils, by whom do your sons G5207 cast them out? therefore shall they be your judges.",
    "Luk 11:30": "For as Jonas was a sign unto the Ninevites, so shall also the Son G5207 of man be to this generation.",
    "Luk 12:8": "Also I say unto you, Whosoever shall confess me before men, him shall the Son G5207 of man also confess before the angels of God:",
    "Luk 12:10": "And whosoever shall speak a word against the Son G5207 of man, it shall be forgiven him: but unto him that blasphemeth against the Holy Ghost it shall not be forgiven.",
    "Luk 12:40": "Be ye therefore ready also: for the Son G5207 of man cometh at an hour when ye think not.",
    "Luk 12:53": "The father shall be divided against the son, G5207 and the son G5207 against the father; the mother against the daughter, and the daughter against the mother; the mother in law against her daughter in law, and the daughter in law against her mother in law.",
    "Luk 15:11": "And he said, A certain man had two sons: G5207",
    "Luk 15:13": "And not many days after the younger son G5207 gathered all together, and took his journey into a far country, and there wasted his substance with riotous living.",
    "Luk 15:19": "And am no more worthy to be called thy son: G5207 make me as one of thy hired servants.",
    "Luk 15:21": "And the son G5207 said unto him, Father, I have sinned against heaven, and in thy sight, and am no more worthy to be called thy son. G5207",
    "Luk 15:24": "For this my son G5207 was dead, and is alive again; he was lost, and is found. And they began to be merry.",
    "Luk 15:25": "Now his elder son G5207 was in the field: and as he came and drew nigh to the house, he heard musick and dancing.",
    "Luk 15:30": "But as soon as this thy son G5207 was come, which hath devoured thy living with harlots, thou hast killed for him the fatted calf.",
    "Luk 16:8": "And the lord commended the unjust steward, because he had done wisely: for the children G5207 of this world are in their generation wiser than the children G5207 of light.",
    "Luk 17:22": "And he said unto the disciples, The days will come, when ye shall desire to see one of the days of the Son G5207 of man, and ye shall not see it.",
    "Luk 17:24": "For as the lightning, that lighteneth out of the one part under heaven, shineth unto the other part under heaven; so shall also the Son G5207 of man be in his day.",
    "Luk 17:26": "And as it was in the days of Noe, so shall it be also in the days of the Son G5207 of man.",
    "Luk 17:30": "Even thus shall it be in the day when the Son G5207 of man is revealed.",
    "Luk 18:8": "I tell you that he will avenge them speedily. Nevertheless when the Son G5207 of man cometh, shall he find faith on the earth?",
    "Luk 18:31": "Then he took unto him the twelve, and said unto them, Behold, we go up to Jerusalem, and all things that are written by the prophets concerning the Son G5207 of man shall be accomplished.",
    "Luk 18:38": "And he cried, saying, Jesus, thou Son G5207 of David, have mercy on me.",
    "Luk 18:39": "And they which went before rebuked him, that he should hold his peace: but he cried so much the more, Thou Son G5207 of David, have mercy on me.",
    "Luk 19:9": "And Jesus said unto him, This day is salvation come to this house, forsomuch as he also is a son G5207 of Abraham.",
    "Luk 19:10": "For the Son G5207 of man is come to seek and to save that which was lost.",
    "Luk 20:13": "Then said the lord of the vineyard, What shall I do? I will send my beloved son: G5207 it may be they will reverence him when they see him.",
    "Luk 20:34": "And Jesus answering said unto them, The children G5207 of this world marry, and are given in marriage:",
    "Luk 20:36": "Neither can they die any more: for they are equal unto the angels; and are the children G5207 of God, being the children G5207 of the resurrection.",
    "Luk 20:41": "And he said unto them, How say they that Christ is David's son? G5207",
    "Luk 20:44": "David therefore calleth him Lord, how is he then his son? G5207",
    "Luk 21:27": "And then shall they see the Son G5207 of man coming in a cloud with power and great glory.",
    "Luk 21:36": "Watch ye therefore, and pray always, that ye may be accounted worthy to escape all these things that shall come to pass, and to stand before the Son G5207 of man.",
    "Luk 22:22": "And truly the Son G5207 of man goeth, as it was determined: but woe unto that man by whom he is betrayed!",
    "Luk 22:48": "But Jesus said unto him, Judas, betrayest thou the Son G5207 of man with a kiss?",
    "Luk 22:69": "Hereafter shall the Son G5207 of man sit on the right hand of the power of God.",
    "Luk 22:70": "Then said they all, Art thou then the Son G5207 of God? And he said unto them, Ye say that I am.",
    "Luk 24:7": "Saying, The Son G5207 of man must be delivered into the hands of sinful men, and be crucified, and the third day rise again.",
    "Jhn 1:18": "No man hath seen God at any time; the only begotten Son, G5207 which is in the bosom of the Father, he hath declared him.",
    "Jhn 1:34": "And I saw, and bare record that this is the Son G5207 of God.",
    "Jhn 1:42": "And he brought him to Jesus. And when Jesus beheld him, he said, Thou art Simon the son G5207 of Jona: thou shalt be called Cephas, which is by interpretation, A stone.",
    "Jhn 1:45": "Philip findeth Nathanael, and saith unto him, We have found him, of whom Moses in the law, and the prophets, did write, Jesus of Nazareth, the son G5207 of Joseph.",
    "Jhn 1:49": "Nathanael answered and saith unto him, Rabbi, thou art the Son G5207 of God; thou art the King of Israel.",
    "Jhn 1:51": "And he saith unto him, Verily, verily, I say unto you, Hereafter ye shall see heaven open, and the angels of God ascending and descending upon the Son G5207 of man.",
    "Jhn 3:13": "And no man hath ascended up to heaven, but he that came down from heaven, even the Son G5207 of man which is in heaven.",
    "Jhn 3:14": "And as Moses lifted up the serpent in the wilderness, even so must the Son G5207 of man be lifted up:",
    "Jhn 3:16": "For God so loved the world, that he gave his only begotten Son, G5207 that whosoever believeth in him should not perish, but have everlasting life.",
    "Jhn 3:17": "For God sent not his Son G5207 into the world to condemn the world; but that the world through him might be saved.",
    "Jhn 3:18": "He that believeth on him is not condemned: but he that believeth not is condemned already, because he hath not believed in the name of the only begotten Son G5207 of God.",
    "Jhn 3:35": "The Father loveth the Son, G5207 and hath given all things into his hand.",
    "Jhn 3:36": "He that believeth on the Son G5207 hath everlasting life: and he that believeth not the Son G5207 shall not see life; but the wrath of God abideth on him.",
    "Jhn 4:5": "Then cometh he to a city of Samaria, which is called Sychar, near to the parcel of ground that Jacob gave to his son G5207 Joseph.",
    "Jhn 4:12": "Art thou greater than our father Jacob, which gave us the well, and drank thereof himself, and his children, G5207 and his cattle?",
    "Jhn 4:46": "So Jesus came again into Cana of Galilee, where he made the water wine. And there was a certain nobleman, whose son G5207 was sick at Capernaum.",
    "Jhn 4:47": "When he heard that Jesus was come out of Judaea into Galilee, he went unto him, and besought him that he would come down, and heal his son: G5207 for he was at the point of death.",
    "Jhn 4:50": "Jesus saith unto him, Go thy way; thy son G5207 liveth. And the man believed the word that Jesus had spoken unto him, and he went his way.",
    "Jhn 4:53": "So the father knew that it was at the same hour, in the which Jesus said unto him, Thy son G5207 liveth: and himself believed, and his whole house.",
    "Jhn 5:19": "Then answered Jesus and said unto them, Verily, verily, I say unto you, The Son G5207 can do nothing of himself, but what he seeth the Father do: for what things soever he doeth, these also doeth the Son G5207 likewise.",
    "Jhn 5:20": "For the Father loveth the Son, G5207 and sheweth him all things that himself doeth: and he will shew him greater works than these, that ye may marvel.",
    "Jhn 5:21": "For as the Father raiseth up the dead, and quickeneth them; even so the Son G5207 quickeneth whom he will.",
    "Jhn 5:22": "For the Father judgeth no man, but hath committed all judgment unto the Son: G5207",
    "Jhn 5:23": "That all men should honour the Son, G5207 even as they honour the Father. He that honoureth not the Son G5207 honoureth not the Father which hath sent him.",
    "Jhn 5:25": "Verily, verily, I say unto you, The hour is coming, and now is, when the dead shall hear the voice of the Son G5207 of God: and they that hear shall live.",
    "Jhn 5:26": "For as the Father hath life in himself; so hath he given to the Son G5207 to have life in himself;",
    "Jhn 5:27": "And hath given him authority to execute judgment also, because he is the Son G5207 of man.",
    "Jhn 6:27": "Labour not for the meat which perisheth, but for that meat which endureth unto everlasting life, which the Son G5207 of man shall give unto you: for him hath God the Father sealed.",
    "Jhn 6:40": "And this is the will of him that sent me, that every one which seeth the Son, G5207 and believeth on him, may have everlasting life: and I will raise him up at the last day.",
    "Jhn 6:42": "And they said, Is not this Jesus, the son G5207 of Joseph, whose father and mother we know? how is it then that he saith, I came down from heaven?",
    "Jhn 6:53": "Then Jesus said unto them, Verily, verily, I say unto you, Except ye eat the flesh of the Son G5207 of man, and drink his blood, ye have no life in you.",
    "Jhn 6:62": "What and if ye shall see the Son G5207 of man ascend up where he was before?",
    "Jhn 6:69": "And we believe and are sure that thou art that Christ, the Son G5207 of the living God.",
    "Jhn 8:28": "Then said Jesus unto them, When ye have lifted up the Son G5207 of man, then shall ye know that I am he, and that I do nothing of myself; but as my Father hath taught me, I speak these things.",
    "Jhn 8:35": "And the servant abideth not in the house for ever: but the Son G5207 abideth ever.",
    "Jhn 8:36": "If the Son G5207 therefore shall make you free, ye shall be free indeed.",
    "Jhn 9:19": "And they asked them, saying, Is this your son, G5207 who ye say was born blind? how then doth he now see?",
    "Jhn 9:20": "His parents answered them and said, We know that this is our son, G5207 and that he was born blind:",
    "Jhn 9:35": "Jesus heard that they had cast him out; and when he had found him, he said unto him, Dost thou believe on the Son G5207 of God?",
    "Jhn 10:36": "Say ye of him, whom the Father hath sanctified, and sent into the world, Thou blasphemest; because I said, I am the Son G5207 of God?",
    "Jhn 11:4": "When Jesus heard that, he said, This sickness is not unto death, but for the glory of God, that the Son G5207 of God might be glorified thereby.",
    "Jhn 11:27": "She saith unto him, Yea, Lord: I believe that thou art the Christ, the Son G5207 of God, which should come into the world.",
    "Jhn 12:23": "And Jesus answered them, saying, The hour is come, that the Son G5207 of man should be glorified.",
    "Jhn 12:34": "The people answered him, We have heard out of the law that Christ abideth for ever: and how sayest thou, The Son G5207 of man must be lifted up? who is this Son G5207 of man?",
    "Jhn 12:36": "While ye have light, believe in the light, that ye may be the children G5207 of light. These things spake Jesus, and departed, and did hide himself from them.",
    "Jhn 13:31": "Therefore, when he was gone out, Jesus said, Now is the Son G5207 of man glorified, and God is glorified in him.",
    "Jhn 14:13": "And whatsoever ye shall ask in my name, that will I do, that the Father may be glorified in the Son. G5207",
    "Jhn 17:1": "These words spake Jesus, and lifted up his eyes to heaven, and said, Father, the hour is come; glorify thy Son, G5207 that thy Son G5207 also may glorify thee:",
    "Jhn 17:12": "While I was with them in the world, I kept them in thy name: those that thou gavest me I have kept, and none of them is lost, but the son G5207 of perdition; that the scripture might be fulfilled.",
    "Jhn 19:7": "The Jews answered him, We have a law, and by our law he ought to die, because he made himself the Son G5207 of God.",
    "Jhn 19:26": "When Jesus therefore saw his mother, and the disciple standing by, whom he loved, he saith unto his mother, Woman, behold thy son! G5207",
    "Jhn 20:31": "But these are written, that ye might believe that Jesus is the Christ, the Son G5207 of God; and that believing ye might have life through his name.",
    "Act 2:17": "And it shall come to pass in the last days, saith God, I will pour out of my Spirit upon all flesh: and your sons G5207 and your daughters shall prophesy, and your young men shall see visions, and your old men shall dream dreams:",
    "Act 3:25": "Ye are the children G5207 of the prophets, and of the covenant which God made with our fathers, saying unto Abraham, And in thy seed shall all the kindreds of the earth be blessed.",
    "Act 4:36": "And Joses, who by the apostles was surnamed Barnabas, (which is, being interpreted, The son G5207 of consolation,) a Levite, and of the country of Cyprus,",
    "Act 5:21": "And when they heard that, they entered into the temple early in the morning, and taught. But the high priest came, and they that were with him, and called the council together, and all the senate of the children G5207 of Israel, and sent to the prison to have them brought.",
    "Act 7:16": "And were carried over into Sychem, and laid in the sepulchre that Abraham bought for a sum of money of the sons G5207 of Emmor the father of Sychem.",
    "Act 7:21": "And when he was cast out, Pharaoh's daughter took him up, and nourished him for her own son. G5207",
    "Act 7:23": "And when he was full forty years old, it came into his heart to visit his brethren the children G5207 of Israel.",
    "Act 7:29": "Then fled Moses at this saying, and was a stranger in the land of Madian, where he begat two sons. G5207",
    "Act 7:37": "This is that Moses, which said unto the children G5207 of Israel, A prophet shall the Lord your God raise up unto you of your brethren, like unto me; him shall ye hear.",
    "Act 7:56": "And said, Behold, I see the heavens opened, and the Son G5207 of man standing on the right hand of God.",
    "Act 8:37": "And Philip said, If thou believest with all thine heart, thou mayest. And he answered and said, I believe that Jesus Christ is the Son G5207 of God.",
    "Act 9:15": "But the Lord said unto him, Go thy way: for he is a chosen vessel unto me, to bear my name before the Gentiles, and kings, and the children G5207 of Israel:",
    "Act 9:20": "And straightway he preached Christ in the synagogues, that he is the Son G5207 of God.",
    "Act 10:36": "The word which God sent unto the children G5207 of Israel, preaching peace by Jesus Christ: (he is Lord of all:)",
    "Act 13:10": "And said, O full of all subtilty and all mischief, thou child G5207 of the devil, thou enemy of all righteousness, wilt thou not cease to pervert the right ways of the Lord?",
    "Act 13:21": "And afterward they desired a king: and God gave unto them Saul the son G5207 of Cis, a man of the tribe of Benjamin, by the space of forty years.",
    "Act 13:26": "Men and brethren, children G5207 of the stock of Abraham, and whosoever among you feareth God, to you is the word of this salvation sent.",
    "Act 13:33": "God hath fulfilled the same unto us their children, in that he hath raised up Jesus again; as it is also written in the second psalm, Thou art my Son, G5207 this day have I begotten thee.",
    "Act 16:1": "Then came he to Derbe and Lystra: and, behold, a certain disciple was there, named Timotheus, the son G5207 of a certain woman, which was a Jewess, and believed; but his father was a Greek:",
    "Act 19:14": "And there were seven sons G5207 of one Sceva, a Jew, and chief of the priests, which did so.",
    "Act 23:6": "But when Paul perceived that the one part were Sadducees, and the other Pharisees, he cried out in the council, Men and brethren, I am a Pharisee, the son G5207 of a Pharisee: of the hope and resurrection of the dead I am called in question.",
    "Act 23:16": "And when Paul's sister's son G5207 heard of their lying in wait, he went and entered into the castle, and told Paul.",
    "Rom 1:3": "Concerning his Son G5207 Jesus Christ our Lord, which was made of the seed of David according to the flesh;",
    "Rom 1:4": "And declared to be the Son G5207 of God with power, according to the spirit of holiness, by the resurrection from the dead:",
    "Rom 1:9": "For God is my witness, whom I serve with my spirit in the gospel of his Son, G5207 that without ceasing I make mention of you always in my prayers;",
    "Rom 5:10": "For if, when we were enemies, we were reconciled to God by the death of his Son, G5207 much more, being reconciled, we shall be saved by his life.",
    "Rom 8:3": "For what the law could not do, in that it was weak through the flesh, God sending his own Son G5207 in the likeness of sinful flesh, and for sin, condemned sin in the flesh:",
    "Rom 8:14": "For as many as are led by the Spirit of God, they are the sons G5207 of God.",
    "Rom 8:19": "For the earnest expectation of the creature waiteth for the manifestation of the sons G5207 of God.",
    "Rom 8:29": "For whom he did foreknow, he also did predestinate to be conformed to the image of his Son, G5207 that he might be the firstborn among many brethren.",
    "Rom 8:32": "He that spared not his own Son, G5207 but delivered him up for us all, how shall he not with him also freely give us all things?",
    "Rom 9:9": "For this is the word of promise, At this time will I come, and Sara shall have a son. G5207",
    "Rom 9:26": "And it shall come to pass, that in the place where it was said unto them, Ye are not my people; there shall they be called the children G5207 of the living God.",
    "Rom 9:27": "Esaias also crieth concerning Israel, Though the number of the children G5207 of Israel be as the sand of the sea, a remnant shall be saved:",
    "1Co 1:9": "God is faithful, by whom ye were called unto the fellowship of his Son G5207 Jesus Christ our Lord.",
    "1Co 15:28": "And when all things shall be subdued unto him, then shall the Son G5207 also himself be subject unto him that put all things under him, that God may be all in all.",
    "2Co 1:19": "For the Son G5207 of God, Jesus Christ, who was preached among you by us, even by me and Silvanus and Timotheus, was not yea and nay, but in him was yea.",
    "2Co 3:7": "But if the ministration of death, written and engraven in stones, was glorious, so that the children G5207 of Israel could not stedfastly behold the face of Moses for the glory of his countenance; which glory was to be done away:",
    "2Co 3:13": "And not as Moses, which put a vail over his face, that the children G5207 of Israel could not stedfastly look to the end of that which is abolished:",
    "2Co 6:18": "And will be a Father unto you, and ye shall be my sons G5207 and daughters, saith the Lord Almighty.",
    "Gal 1:16": "To reveal his Son G5207 in me, that I might preach him among the heathen; immediately I conferred not with flesh and blood:",
    "Gal 2:20": "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son G5207 of God, who loved me, and gave himself for me.",
    "Gal 3:7": "Know ye therefore that they which are of faith, the same are the children G5207 of Abraham.",
    "Gal 3:26": "For ye are all the children G5207 of God by faith in Christ Jesus.",
    "Gal 4:4": "But when the fulness of the time was come, God sent forth his Son, G5207 made of a woman, made under the law,",
    "Gal 4:6": "And because ye are sons, G5207 God hath sent forth the Spirit of his Son G5207 into your hearts, crying, Abba, Father.",
    "Gal 4:7": "Wherefore thou art no more a servant, but a son; G5207 and if a son, G5207 then an heir of God through Christ.",
    "Gal 4:22": "For it is written, that Abraham had two sons, G5207 the one by a bondmaid, the other by a freewoman.",
    "Gal 4:30": "Nevertheless what saith the scripture? Cast out the bondwoman and her son: G5207 for the son G5207 of the bondwoman shall not be heir with the son G5207 of the freewoman.",
    "Eph 2:2": "Wherein in time past ye walked according to the course of this world, according to the prince of the power of the air, the spirit that now worketh in the children G5207 of disobedience:",
    "Eph 3:5": "Which in other ages was not made known unto the sons G5207 of men, as it is now revealed unto his holy apostles and prophets by the Spirit;",
    "Eph 4:13": "Till we all come in the unity of the faith, and of the knowledge of the Son G5207 of God, unto a perfect man, unto the measure of the stature of the fulness of Christ:",
    "Eph 5:6": "Let no man deceive you with vain words: for because of these things cometh the wrath of God upon the children G5207 of disobedience.",
    "Col 1:13": "Who hath delivered us from the power of darkness, and hath translated us into the kingdom of his dear Son: G5207",
    "Col 3:6": "For which things' sake the wrath of God cometh on the children G5207 of disobedience:",
    "1Th 1:10": "And to wait for his Son G5207 from heaven, whom he raised from the dead, even Jesus, which delivered us from the wrath to come.",
    "1Th 5:5": "Ye are all the children G5207 of light, and the children G5207 of the day: we are not of the night, nor of darkness.",
    "2Th 2:3": "Let no man deceive you by any means: for that day shall not come, except there come a falling away first, and that man of sin be revealed, the son G5207 of perdition;",
    "Heb 1:2": "Hath in these last days spoken unto us by his Son, G5207 whom he hath appointed heir of all things, by whom also he made the worlds;",
    "Heb 1:5": "For unto which of the angels said he at any time, Thou art my Son, G5207 this day have I begotten thee? And again, I will be to him a Father, and he shall be to me a Son? G5207",
    "Heb 1:8": "But unto the Son G5207 he saith, Thy throne, O God, is for ever and ever: a sceptre of righteousness is the sceptre of thy kingdom.",
    "Heb 2:6": "But one in a certain place testified, saying, What is man, that thou art mindful of him? or the son G5207 of man, that thou visitest him?",
    "Heb 2:10": "For it became him, for whom are all things, and by whom are all things, in bringing many sons G5207 unto glory, to make the captain of their salvation perfect through sufferings.",
    "Heb 3:6": "But Christ as a son G5207 over his own house; whose house are we, if we hold fast the confidence and the rejoicing of the hope firm unto the end.",
    "Heb 4:14": "Seeing then that we have a great high priest, that is passed into the heavens, Jesus the Son G5207 of God, let us hold fast our profession.",
    "Heb 5:5": "So also Christ glorified not himself to be made an high priest; but he that said unto him, Thou art my Son, G5207 to day have I begotten thee.",
    "Heb 5:8": "Though he were a Son, G5207 yet learned he obedience by the things which he suffered;",
    "Heb 6:6": "If they shall fall away, to renew them again unto repentance; seeing they crucify to themselves the Son G5207 of God afresh, and put him to an open shame.",
    "Heb 7:3": "Without father, without mother, without descent, having neither beginning of days, nor end of life; but made like unto the Son G5207 of God; abideth a priest continually.",
    "Heb 7:5": "And verily they that are of the sons G5207 of Levi, who receive the office of the priesthood, have a commandment to take tithes of the people according to the law, that is, of their brethren, though they come out of the loins of Abraham:",
    "Heb 7:28": "For the law maketh men high priests which have infirmity; but the word of the oath, which was since the law, maketh the Son, G5207 who is consecrated for evermore.",
    "Heb 10:29": "Of how much sorer punishment, suppose ye, shall he be thought worthy, who hath trodden under foot the Son G5207 of God, and hath counted the blood of the covenant, wherewith he was sanctified, an unholy thing, and hath done despite unto the Spirit of grace?",
    "Heb 11:21": "By faith Jacob, when he was a dying, blessed both the sons G5207 of Joseph; and worshipped, leaning upon the top of his staff.",
    "Heb 11:22": "By faith Joseph, when he died, made mention of the departing of the children G5207 of Israel; and gave commandment concerning his bones.",
    "Heb 11:24": "By faith Moses, when he was come to years, refused to be called the son G5207 of Pharaoh's daughter;",
    "Heb 12:5": "And ye have forgotten the exhortation which speaketh unto you as unto children, G5207 My son, G5207 despise not thou the chastening of the Lord, nor faint when thou art rebuked of him:",
    "Heb 12:6": "For whom the Lord loveth he chasteneth, and scourgeth every son G5207 whom he receiveth.",
    "Heb 12:7": "If ye endure chastening, God dealeth with you as with sons; G5207 for what son G5207 is he whom the father chasteneth not?",
    "Heb 12:8": "But if ye be without chastisement, whereof all are partakers, then are ye bastards, and not sons. G5207",
    "Jas 2:21": "Was not Abraham our father justified by works, when he had offered Isaac his son G5207 upon the altar?",
    "1Pe 5:13": "The church that is at Babylon, elected together with you, saluteth you; and so doth Marcus my son. G5207",
    "2Pe 1:17": "For he received from God the Father honour and glory, when there came such a voice to him from the excellent glory, This is my beloved Son, G5207 in whom I am well pleased.",
    "1Jo 1:3": "That which we have seen and heard declare we unto you, that ye also may have fellowship with us: and truly our fellowship is with the Father, and with his Son G5207 Jesus Christ.",
    "1Jo 1:7": "But if we walk in the light, as he is in the light, we have fellowship one with another, and the blood of Jesus Christ his Son G5207 cleanseth us from all sin.",
    "1Jo 2:22": "Who is a liar but he that denieth that Jesus is the Christ? He is antichrist, that denieth the Father and the Son. G5207",
    "1Jo 2:23": "Whosoever denieth the Son, G5207 the same hath not the Father: (but) he that acknowledgeth the Son G5207 hath the Father also.",
    "1Jo 2:24": "Let that therefore abide in you, which ye have heard from the beginning. If that which ye have heard from the beginning shall remain in you, ye also shall continue in the Son, G5207 and in the Father.",
    "1Jo 3:8": "He that committeth sin is of the devil; for the devil sinneth from the beginning. For this purpose the Son G5207 of God was manifested, that he might destroy the works of the devil.",
    "1Jo 3:23": "And this is his commandment, That we should believe on the name of his Son G5207 Jesus Christ, and love one another, as he gave us commandment.",
    "1Jo 4:9": "In this was manifested the love of God toward us, because that God sent his only begotten Son G5207 into the world, that we might live through him.",
    "1Jo 4:10": "Herein is love, not that we loved God, but that he loved us, and sent his Son G5207 to be the propitiation for our sins.",
    "1Jo 4:14": "And we have seen and do testify that the Father sent the Son G5207 to be the Saviour of the world.",
    "1Jo 4:15": "Whosoever shall confess that Jesus is the Son G5207 of God, God dwelleth in him, and he in God.",
    "1Jo 5:5": "Who is he that overcometh the world, but he that believeth that Jesus is the Son G5207 of God?",
    "1Jo 5:9": "If we receive the witness of men, the witness of God is greater: for this is the witness of God which he hath testified of his Son. G5207",
    "1Jo 5:10": "He that believeth on the Son G5207 of God hath the witness in himself: he that believeth not God hath made him a liar; because he believeth not the record that God gave of his Son. G5207",
    "1Jo 5:11": "And this is the record, that God hath given to us eternal life, and this life is in his Son. G5207",
    "1Jo 5:12": "He that hath the Son G5207 hath life; and he that hath not the Son G5207 of God hath not life.",
    "1Jo 5:13": "These things have I written unto you that believe on the name of the Son G5207 of God; that ye may know that ye have eternal life, and that ye may believe on the name of the Son G5207 of God.",
    "1Jo 5:20": "And we know that the Son G5207 of God is come, and hath given us an understanding, that we may know him that is true, and we are in him that is true, even in his Son G5207 Jesus Christ. This is the true God, and eternal life.",
    "2Jo 1:3": "Grace be with you, mercy, and peace, from God the Father, and from the Lord Jesus Christ, the Son G5207 of the Father, in truth and love.",
    "2Jo 1:9": "Whosoever transgresseth, and abideth not in the doctrine of Christ, hath not God. He that abideth in the doctrine of Christ, he hath both the Father and the Son. G5207",
    "Rev 1:13": "And in the midst of the seven candlesticks one like unto the Son G5207 of man, clothed with a garment down to the foot, and girt about the paps with a golden girdle.",
    "Rev 2:14": "But I have a few things against thee, because thou hast there them that hold the doctrine of Balaam, who taught Balac to cast a stumblingblock before the children G5207 of Israel, to eat things sacrificed unto idols, and to commit fornication.",
    "Rev 2:18": "And unto the angel of the church in Thyatira write; These things saith the Son G5207 of God, who hath his eyes like unto a flame of fire, and his feet are like fine brass;",
    "Rev 7:4": "And I heard the number of them which were sealed: and there were sealed an hundred and forty and four thousand of all the tribes of the children G5207 of Israel.",
    "Rev 12:5": "And she brought forth a man child, G5207 who was to rule all nations with a rod of iron: and her child was caught up unto God, and to his throne.",
    "Rev 14:14": "And I looked, and behold a white cloud, and upon the cloud one sat like unto the Son G5207 of man, having on his head a golden crown, and in his hand a sharp sickle.",
    "Rev 21:7": "He that overcometh shall inherit all things; and I will be his God, and he shall be my son. G5207",
    "Rev 21:12": "And had a wall great and high, and had twelve gates, and at the gates twelve angels, and names written thereon, which are the names of the twelve tribes of the children G5207 of Israel:"
}